import Head from 'next/head'
import { useState } from 'react'
// import Image from 'next/image'
import styles from '../styles/Home.module.css'
import axios from 'axios';

export default function Home() {
  const [file, setFile] = useState();

  const sendFile = async () => {
    let formData = new FormData()
    formData.append('file1', file);

    const res = await axios.get('http://localhost:8000/');
    console.log(res.data);

    const res2 = await axios.request({ 
      method: 'post',
      url: 'http://localhost:8000/file',
      body: {
        'file': file
      }
    });
    console.log(res2);
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>qc-judge</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <input
          type="file"
          id="avatarInput"
          onChange={(e) => setFile(e.target.files[0])}
        />
        <button onClick={sendFile}>upload</button>
      </main>

      <footer className={styles.footer}>

      </footer>
    </div>
  )
}
