import Head from 'next/head'
import { useState } from 'react'
// import Image from 'next/image'
import styles from '../styles/Home.module.css'
import axios from 'axios';

export default function Home() {
  const [file, setFile] = useState();
  const [response, setResponse] = useState('We wish for your success!!');

  const sendFile = async () => {
    let formData = new FormData();
    formData.append('file', file);

    const res = await axios.get('http://localhost:8000/');
    setResponse('loading...');
    const res2 = await axios.post('http://localhost:8000/file', formData, {
      headers: {
        'Content-Type': 'multipart/form-data'
      }
    });
    console.log(res2.data);
    setResponse(res2.data.QC);
  }

  const message = (response) => {
    if (response >= 0.99) {
      return ('QC existence');
    }else if (response < 0.99) {
      return ('QC absence');
    }else {
      return ('');
    }
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>qc-judge</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <input
          type="file"
          id="avatarInput"
          onChange={(e) => setFile(e.target.files[0])}
        />
        <button onClick={sendFile}>upload</button>
        <p>{message(response)}</p>
        <p>{response}</p>
      </main>

      <footer className={styles.footer}>

      </footer>
    </div>
  )
}
