import Head from 'next/head'
import { useState } from 'react'
import styles from '../styles/Home.module.css'
import axios from 'axios';

export default function Home() {
  const [files, setFiles] = useState();
  const [response, setResponse] = useState('We wish for your success!!');
  const [progress, setProgress] = useState('0%');

  const sendFile = async () => {
    setResponse('loading...');
    let formData = new FormData();
    for (let i = 0; i < files.length; i ++) {
      formData.append("files", files[i]);
    }


    const res = await axios.post('http://localhost:8000/file', formData, {
      headers: {
        'Content-Type': 'multipart/form-data'
      }
    });

    console.log(res);
    setResponse(res.data.QC);

    let prog = await axios.get('http://localhost:8000/progress');
    setProgress(prog)
  }

  const message = (response) => {
    if (response >= 0.99) {
      return ('QC existence');
    }else if (response < 0.99) {
      return ('QC absence');
    }else {
      return ('');
    }
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>high-thoroughput-QC-detection</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <input
          type="file"
          id="avatarInput"
          onChange={(e) => setFiles(e.target.files)}
          directory=""
          webkitdirectory=""
        />
        <button onClick={sendFile}>upload</button>
        <p>{message(response)}</p>
        <p>{response}</p>
        <p>{progress}</p>
      </main>

      <footer className={styles.footer}>

      </footer>
    </div>
  )
}
